# ????????? API
api.base.url=https://archive-api.open-meteo.com/v1/archive

# ?????????? ??????? (?????????? ?? ?????????)
spb.name=Saint Petersburg
spb.lat=59.9386
spb.lon=30.3141

cherepovets.name=Cherepovets
cherepovets.lat=59.1293
cherepovets.lon=37.9524